import sys, os, json
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from agents.risk_deadline import risk_agent
from langchain_core.messages import ToolMessage
from tools.risk_tools import calculate_days_remaining, check_dependency_status, assess_progress_risk

class SimpleMessage:
    def __init__(self, content):
        self.content = content

# ---------- MEMORY ----------
past_findings = []

def store_finding(finding):
    past_findings.append(finding)

def get_recent_findings(n=3):
    return past_findings[-n:]

# ---------- PLANNING MODULE ----------
def plan_analysis_steps(task):
    """Decides which tools/steps are needed for this task before analysis runs."""
    steps = ["calculate_days_remaining"]
    if task.get("depends_on"):
        steps.append("check_dependency_status")
    steps.append("assess_progress_risk")
    return steps

# ---------- OUTPUT / RESPONSE FORMATTING ----------
def format_user_response(task_id, finding, tool_outputs):
    if finding == "high_risk":
        dep_note = tool_outputs.get("check_dependency_status", "")
        extra = f" ({dep_note})" if "behind" in dep_note.lower() else ""
        return f"[HIGH RISK] Task {task_id} needs attention.{extra}"
    return f"[ON TRACK] Task {task_id} is progressing well."

# ---------- MOCK RESPONSE (bypasses LLM, deterministic) ----------
def make_mock_response(task, project_data):
    days = calculate_days_remaining(task["planned_end"])
    dependency_status = check_dependency_status(task["id"], project_data["tasks"])
    assess = assess_progress_risk(task["progress_pct"], days)
    finding = "high_risk" if assess.startswith("high_risk") or days <= 0 or "behind schedule" in dependency_status.lower() else "on_track"
    llm_text = (
        f"Finding: {finding}\n"
        f"Confidence: 1.0\n"
        f"Reason: Generated by mock local stub based on tool outputs."
    )
    return {
        "messages": [
            ToolMessage(name="calculate_days_remaining", content=str(days), tool_call_id="mock_1"),
            ToolMessage(name="check_dependency_status", content=dependency_status, tool_call_id="mock_2"),
            ToolMessage(name="assess_progress_risk", content=assess, tool_call_id="mock_3"),
            SimpleMessage(content=llm_text),
        ]
    }

# ---------- MAIN AGENT RUNNER ----------
def run_risk_agent(project_data):
    findings = []
    use_mock = os.getenv("USE_MOCK_AGENT", "0") == "1"

    for task in project_data["tasks"]:
        # PLANNING happens before execution
        steps = plan_analysis_steps(task)

        if use_mock:
            response = make_mock_response(task, project_data)
        else:
            prompt = f"Analyze this task: {task}. Full task list (only for dependency checks): {project_data['tasks']}"
            response = risk_agent.invoke({"messages": [{"role": "user", "content": prompt}]})

        tool_outputs = {}
        for m in response["messages"]:
            if isinstance(m, ToolMessage):
                tool_outputs[m.name] = m.content

        llm_explanation = ""
        llm_finding = ""
        for m in reversed(response["messages"]):
            if not isinstance(m, ToolMessage):
                llm_explanation = m.content
                if m.content:
                    for line in m.content.splitlines():
                        if line.strip().lower().startswith("finding:"):
                            llm_finding = line.split(":", 1)[1].strip().lower()
                            break
                break

        days_remaining_str = tool_outputs.get("calculate_days_remaining", "0")
        try:
            days_remaining = int(days_remaining_str)
        except ValueError:
            days_remaining = 0

        dependency_result = tool_outputs.get("check_dependency_status", "").lower()
        dependency_issue = "behind schedule" in dependency_result

        assess_result = tool_outputs.get("assess_progress_risk", "").lower()
        if assess_result.startswith("high_risk"):
            real_finding = "high_risk"
        elif days_remaining <= 0 or dependency_issue:
            real_finding = "high_risk"
        else:
            real_finding = "on_track"

        # OUTPUT formatting
        user_response = format_user_response(task["id"], real_finding, tool_outputs)

        finding_record = {
            "agent": "risk_deadline",
            "task_id": task["id"],
            "planned_steps": steps,
            "finding": real_finding,
            "llm_finding": llm_finding,
            "llm_explanation": llm_explanation,
            "raw_tool_outputs": tool_outputs,
            "conflict": bool(llm_finding and llm_finding != real_finding),
            "user_response": user_response
        }

        # MEMORY: store this finding for future recall
        store_finding(finding_record)
        findings.append(finding_record)

    return findings

def orchestrate(project_data):
    all_findings = []
    all_findings.extend(run_risk_agent(project_data))
    return all_findings

if __name__ == "__main__":
    with open("data/sample_project.json") as f:
        project_data = json.load(f)

    results = orchestrate(project_data)
    print("=== Orchestrator Report ===\n")
    for r in results:
        print(f"[{r['agent']}] {r['task_id']}")
        print(f"  Planned steps: {r['planned_steps']}")
        print(f"  VERIFIED Finding: {r['finding']}")
        if r.get("conflict"):
            print(f"  ⚠️ CONFLICT: LLM said '{r.get('llm_finding')}' but tools indicate '{r['finding']}'")
        print(f"  Tool outputs: {r['raw_tool_outputs']}")
        print(f"  User-facing response: {r['user_response']}")
        print()

    print("=== Memory: recent findings stored ===")
    for f in get_recent_findings():
        print(f"  {f['task_id']}: {f['finding']}")