import sys, os, json
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import json as json_lib

from agents.risk_deadline import risk_agent
from langchain_core.messages import ToolMessage
from tools.risk_tools import calculate_days_remaining, check_dependency_status, assess_progress_risk
from tools.resource_tools import calculate_utilization
from tools.budget_tools import check_budget_status, check_threshold_alerts
from tools.allocation_tools import recommend_assignee
from db.session import init_db
from db.repository import save_finding, get_recent_findings as db_get_recent_findings
from tools.scrum_tools import check_sprint_progress, flag_impediments
from tools.distribution_tools import analyze_workload_distribution
class SimpleMessage:
    def __init__(self, content):
        self.content = content

# ---------- MEMORY ----------
# ---------- MEMORY (now persistent via database) ----------
init_db()  # creates tables if they don't exist yet, safe to call every run

def store_finding(finding, project_id):
    """Persist a finding to the database instead of an in-memory list."""
    target = finding.get("task_id") or finding.get("member") or "unknown"
    save_finding(
        project_id=project_id,
        agent_name=finding["agent"],
        target=target,
        finding=finding["finding"],
        details={"user_response": finding.get("user_response", "")}
    )

def get_recent_findings(project_id, n=5):
    """Pull real historical findings back from the database."""
    return db_get_recent_findings(project_id, limit=n)

# ---------- PLANNING MODULE ----------
def plan_analysis_steps(task):
    """Decides which tools/steps are needed for this task before analysis runs."""
    steps = ["calculate_days_remaining"]
    if task.get("depends_on"):
        steps.append("check_dependency_status")
    steps.append("assess_progress_risk")
    return steps

# ---------- OUTPUT / RESPONSE FORMATTING ----------
def format_user_response(task_id, finding, tool_outputs):
    if finding == "high_risk":
        dep_note = tool_outputs.get("check_dependency_status", "")
        extra = f" ({dep_note})" if dep_note.lower().startswith("dependency issues") else ""
        return f"[HIGH RISK] Task {task_id} needs attention.{extra}"
    return f"[ON TRACK] Task {task_id} is progressing well."

# ---------- MOCK RESPONSE (bypasses LLM, deterministic) ----------
def make_mock_response(task, project_data):
    days = calculate_days_remaining(task["planned_end"])
    dependency_status = check_dependency_status(task["id"], project_data["tasks"])
    assess = assess_progress_risk(task["progress_pct"], days)
    finding = "high_risk" if assess.startswith("high_risk") or days <= 0 or "behind schedule" in dependency_status.lower() else "on_track"
    llm_text = (
        f"Finding: {finding}\n"
        f"Confidence: 1.0\n"
        f"Reason: Generated by mock local stub based on tool outputs."
    )
    return {
        "messages": [
            ToolMessage(name="calculate_days_remaining", content=str(days), tool_call_id="mock_1"),
            ToolMessage(name="check_dependency_status", content=dependency_status, tool_call_id="mock_2"),
            ToolMessage(name="assess_progress_risk", content=assess, tool_call_id="mock_3"),
            SimpleMessage(content=llm_text),
        ]
    }
def make_mock_allocation_response(candidates, required_skill=None):
    from tools.allocation_tools import recommend_assignee
    result = recommend_assignee(candidates, required_skill=required_skill)
    llm_text = f"Finding: {result}\nConfidence: 1.0\nReason: Generated by mock local stub."
    return {
        "messages": [
            ToolMessage(name="recommend_assignee", content=result, tool_call_id="mock_a1"),
            SimpleMessage(content=llm_text),
        ]
    }


# ---------- MAIN AGENT RUNNER ----------
def run_risk_agent(project_data, project_id):
    findings = []
    use_mock = os.getenv("USE_MOCK_AGENT", "0") == "1"

    for task in project_data["tasks"]:
        # PLANNING happens before execution
        steps = plan_analysis_steps(task)

        if use_mock:
            response = make_mock_response(task, project_data)
        else:
            prompt = f"Analyze this task: {task}. Full task list (only for dependency checks): {project_data['tasks']}"
            response = risk_agent.invoke({"messages": [{"role": "user", "content": prompt}]})

        tool_outputs = {}
        for m in response["messages"]:
            if isinstance(m, ToolMessage):
                tool_outputs[m.name] = m.content

        llm_explanation = ""
        llm_finding = ""
        for m in reversed(response["messages"]):
            if not isinstance(m, ToolMessage):
                llm_explanation = m.content
                if m.content:
                    for line in m.content.splitlines():
                        if line.strip().lower().startswith("finding:"):
                            llm_finding = line.split(":", 1)[1].strip().lower()
                            break
                break

        days_remaining_str = tool_outputs.get("calculate_days_remaining", "0")
        try:
            days_remaining = int(days_remaining_str)
        except ValueError:
            days_remaining = 0

        dependency_result = tool_outputs.get("check_dependency_status", "").lower()
        dependency_issue = dependency_result.startswith("dependency issues") 
        assess_result = tool_outputs.get("assess_progress_risk", "").lower()
        if assess_result.startswith("high_risk"):
            real_finding = "high_risk"
        elif days_remaining <= 0 or dependency_issue:
            real_finding = "high_risk"
        else:
            real_finding = "on_track"

        # OUTPUT formatting
        user_response = format_user_response(task["id"], real_finding, tool_outputs)

        finding_record = {
            "agent": "risk_deadline",
            "task_id": task["id"],
            "planned_steps": steps,
            "finding": real_finding,
            "llm_finding": llm_finding,
            "llm_explanation": llm_explanation,
            "raw_tool_outputs": tool_outputs,
            "conflict": bool(llm_finding and llm_finding != real_finding),
            "user_response": user_response
        }

        # MEMORY: store this finding for future recall
        store_finding(finding_record, project_id)
        findings.append(finding_record)

    return findings


def make_mock_resource_response(member):
    result = calculate_utilization(member["logged_hrs_week"], member["capacity_hrs_week"])
    finding = "overloaded" if "overloaded" in result else "available"
    llm_text = f"Finding: {finding}\nConfidence: 1.0\nReason: Generated by mock local stub."
    return {
        "messages": [
            ToolMessage(name="calculate_utilization", content=result, tool_call_id="mock_r1"),
            SimpleMessage(content=llm_text),
        ]
    }

def run_resource_agent(project_data, project_id):
    findings = []
    use_mock = os.getenv("USE_MOCK_AGENT", "0") == "1"
    for member in project_data.get("team", []):
        if use_mock:
            response = make_mock_resource_response(member)
        else:
            prompt = f"Check utilization for {member['name']}: logged {member['logged_hrs_week']} hrs, capacity {member['capacity_hrs_week']} hrs."
            from agents.resource_usage import resource_agent
            response = resource_agent.invoke({"messages": [{"role": "user", "content": prompt}]})

        tool_outputs = {}
        for m in response["messages"]:
            if isinstance(m, ToolMessage):
                tool_outputs[m.name] = m.content

        util_result = tool_outputs.get("calculate_utilization", "")
        if "severely_overloaded" in util_result:
            finding = "severely_overloaded"
        elif "overloaded" in util_result:
            finding = "overloaded"
        elif "near_capacity" in util_result:
            finding = "near_capacity"
        else:
            finding = "available"

        finding_record = {
            "agent": "resource_usage",
            "member": member["name"],
            "finding": finding,
            "raw_tool_outputs": tool_outputs,
            "user_response": f"{'⚠️' if finding == 'overloaded' else '✅'} {member['name']} is {finding} ({util_result})".replace("⚠️", "[OVERLOADED]").replace("✅", "[OK]")
        }
        store_finding(finding_record, project_id)
        findings.append(finding_record)
    return findings

def make_mock_budget_response(budget):
    result = check_budget_status(budget["planned_spend"], budget["actual_spend"], budget["pct_time_elapsed"])
    pct_spent = (budget["actual_spend"] / budget["planned_spend"]) * 100
    alert = check_threshold_alerts(pct_spent)

    if result.startswith("over_budget"):
        finding = "over_budget"
    elif result.startswith("at_risk"):
        finding = "at_risk"
    else:
        finding = "on_budget"

    llm_text = f"Finding: {finding}\nConfidence: 1.0\nReason: Generated by mock local stub."
    return {
        "messages": [
            ToolMessage(name="check_budget_status", content=result, tool_call_id="mock_b1"),
            ToolMessage(name="check_threshold_alerts", content=alert, tool_call_id="mock_b2"),
            SimpleMessage(content=llm_text),
        ]
    }
def run_budget_agent(project_data, project_id):
    findings = []
    budget = project_data.get("budget")
    if not budget:
        return findings

    use_mock = os.getenv("USE_MOCK_AGENT", "0") == "1"
    if use_mock:
        response = make_mock_budget_response(budget)
    else:
        prompt = f"Check budget: planned_spend={budget['planned_spend']}, actual_spend={budget['actual_spend']}, pct_time_elapsed={budget['pct_time_elapsed']}."
        from agents.budget_tracking import budget_agent
        response = budget_agent.invoke({"messages": [{"role": "user", "content": prompt}]})

    tool_outputs = {}
    for m in response["messages"]:
        if isinstance(m, ToolMessage):
            tool_outputs[m.name] = m.content

    result = tool_outputs.get("check_budget_status", "")
    if result.startswith("over_budget"):
        finding = "over_budget"
    elif result.startswith("at_risk"):
        finding = "at_risk"
    else:
        finding = "on_budget"

    alert = tool_outputs.get("check_threshold_alerts", "")
    alert_note = f" | {alert}" if alert.startswith(("ALERT", "WARNING")) else ""

    label = finding.replace("_", " ").upper()
    finding_record = {
        "agent": "budget_tracking",
        "member": "Overall Project",
        "finding": finding,
        "raw_tool_outputs": tool_outputs,
        "user_response": f"[{label}] Project spend: {result}{alert_note}"
    }
    store_finding(finding_record, project_id)
    findings.append(finding_record)
    return findings

def get_reassignment_suggestion(project_data, exclude_person=None, required_skill=None):
    """Ask the Task Allocation agent who should take over a task, excluding the overloaded person."""
    candidates = []
    for member in project_data.get("team", []):
        if member["name"] == exclude_person:
            continue
        pct = (member["logged_hrs_week"] / member["capacity_hrs_week"]) * 100
        candidates.append({
            "name": member["name"],
            "utilization_pct": round(pct),
            "skills": member.get("skills", [])
        })

    if not candidates:
        return "No alternative team member available"

    use_mock = os.getenv("USE_MOCK_AGENT", "0") == "1"
    if use_mock:
        response = make_mock_allocation_response(candidates, required_skill=required_skill)
    else:
        skill_note = f" The task requires the skill: {required_skill}." if required_skill else ""
        prompt = f"Candidates: {json_lib.dumps(candidates)}.{skill_note} Who should take this task?"
        from agents.task_allocation import allocation_agent
        response = allocation_agent.invoke({"messages": [{"role": "user", "content": prompt}]})

    for m in response["messages"]:
        if isinstance(m, ToolMessage) and m.name == "recommend_assignee":
            return m.content
    return "Could not determine a recommendation"

def make_mock_scrum_response(tasks):
    progress_summary = check_sprint_progress(tasks)
    impediments = flag_impediments(tasks)
    finding = "impediments_found" if impediments.startswith("Impediments found") else "healthy"
    llm_text = f"Finding: {finding}\nConfidence: 1.0\nReason: Generated by mock local stub."
    return {
        "messages": [
            ToolMessage(name="check_sprint_progress", content=progress_summary, tool_call_id="mock_s1"),
            ToolMessage(name="flag_impediments", content=impediments, tool_call_id="mock_s2"),
            SimpleMessage(content=llm_text),
        ]
    }

def run_scrum_master_agent(project_data, project_id):
    findings = []
    tasks = project_data.get("tasks", [])
    if not tasks:
        return findings

    use_mock = os.getenv("USE_MOCK_AGENT", "0") == "1"
    if use_mock:
        response = make_mock_scrum_response(tasks)
    else:
        prompt = f"Evaluate this sprint's tasks: {tasks}"
        from agents.scrum_master import scrum_master_agent
        response = scrum_master_agent.invoke({"messages": [{"role": "user", "content": prompt}]})

    tool_outputs = {}
    for m in response["messages"]:
        if isinstance(m, ToolMessage):
            tool_outputs[m.name] = m.content

    impediments_result = tool_outputs.get("flag_impediments", "")
    finding = "impediments_found" if impediments_result.startswith("Impediments found") else "healthy"

    finding_record = {
        "agent": "scrum_master",
        "member": "Sprint Overview",
        "finding": finding,
        "raw_tool_outputs": tool_outputs,
        "user_response": f"[{'IMPEDIMENTS' if finding == 'impediments_found' else 'HEALTHY'}] "
                          f"{tool_outputs.get('check_sprint_progress', '')} | {impediments_result}"
    }
    store_finding(finding_record, project_id)
    findings.append(finding_record)
    return findings

def make_mock_distribution_response(team):
    result = analyze_workload_distribution(team)
    finding = "imbalanced" if result.startswith("Imbalanced") else "balanced"
    llm_text = f"Finding: {finding}\nConfidence: 1.0\nReason: Generated by mock local stub."
    return {
        "messages": [
            ToolMessage(name="analyze_workload_distribution", content=result, tool_call_id="mock_d1"),
            SimpleMessage(content=llm_text),
        ]
    }

def run_distribution_agent(project_data, project_id):
    findings = []
    team = project_data.get("team", [])
    if not team:
        return findings

    use_mock = os.getenv("USE_MOCK_AGENT", "0") == "1"
    if use_mock:
        response = make_mock_distribution_response(team)
    else:
        prompt = f"Analyze this team's workload distribution: {json_lib.dumps(team)}"
        from agents.project_distribution import distribution_agent
        response = distribution_agent.invoke({"messages": [{"role": "user", "content": prompt}]})

    tool_outputs = {}
    for m in response["messages"]:
        if isinstance(m, ToolMessage):
            tool_outputs[m.name] = m.content

    result = tool_outputs.get("analyze_workload_distribution", "")
    if result.startswith("Imbalanced") or result.startswith("Overloaded"):
        finding = "imbalanced"
    else:
        finding = "balanced"

    finding_record = {
        "agent": "project_distribution",
        "member": "Team Overview",
        "finding": finding,
        "raw_tool_outputs": tool_outputs,
        "user_response": f"[{'IMBALANCED' if finding == 'imbalanced' else 'BALANCED'}] {result}"
    }
    store_finding(finding_record, project_id)
    findings.append(finding_record)
    return findings

def resolve_conflicts(all_findings, project_data):
    """Cross-reference risk, resource, budget, scrum, and distribution findings."""
    task_to_assignee = {t["id"]: t.get("assigned_to") for t in project_data["tasks"]}
    task_to_skill = {t["id"]: t.get("required_skill") for t in project_data["tasks"]}
    risk_findings = [f for f in all_findings if f["agent"] == "risk_deadline"]
    resource_findings = {f["member"]: f for f in all_findings if f["agent"] == "resource_usage"}
    budget_findings = [f for f in all_findings if f["agent"] == "budget_tracking"]
    scrum_findings = [f for f in all_findings if f["agent"] == "scrum_master"]
    distribution_findings = [f for f in all_findings if f["agent"] == "project_distribution"]

    is_over_budget = any(f["finding"] in ("over_budget", "at_risk") for f in budget_findings)
    has_impediments = any(f["finding"] == "impediments_found" for f in scrum_findings)
    is_imbalanced = any(f["finding"] == "imbalanced" for f in distribution_findings)

    # Extract which specific task IDs the Scrum Master flagged as impediments
    impeded_task_ids = set()
    for f in scrum_findings:
        impediments_text = f.get("raw_tool_outputs", {}).get("flag_impediments", "")
        for tid in task_to_assignee.keys():
            if tid in impediments_text:
                impeded_task_ids.add(tid)

    conflicts = []
    for rf in risk_findings:
        if rf["finding"] != "high_risk":
            continue
        assignee = task_to_assignee.get(rf["task_id"])
        overloaded = assignee and assignee in resource_findings and resource_findings[assignee]["finding"] in ("overloaded", "severely_overloaded")
        is_impeded = rf["task_id"] in impeded_task_ids

        # Build extra context notes that apply regardless of which branch below fires
        extra_notes = []
        if is_impeded:
            extra_notes.append("also flagged as a sprint impediment - this is blocking sprint progress, not just a deadline risk")
        if is_imbalanced and overloaded:
            extra_notes.append("this is part of a broader team-wide workload imbalance, not an isolated case")
        extra_note_str = (" Additionally, " + "; ".join(extra_notes) + ".") if extra_notes else ""

        if overloaded and is_over_budget:
            suggestion = get_reassignment_suggestion(project_data, exclude_person=assignee, required_skill=task_to_skill.get(rf["task_id"]))
            conflicts.append({
                "task_id": rf["task_id"],
                "assignee": assignee,
                "issue": f"Task {rf['task_id']} is high-risk, {assignee} is overloaded, AND the project is over budget",
                "recommendation": f"Highest priority: reassign task {rf['task_id']} away from {assignee}. {suggestion}. "
                                   f"Avoid hiring/contracting extra help given budget pressure - redistribute existing workload instead."
                                   f"{extra_note_str}"
            })
        elif overloaded:
            suggestion = get_reassignment_suggestion(project_data, exclude_person=assignee, required_skill=task_to_skill.get(rf["task_id"]))
            conflicts.append({
                "task_id": rf["task_id"],
                "assignee": assignee,
                "issue": f"Task {rf['task_id']} is high-risk, but {assignee} is already overloaded "
                         f"({resource_findings[assignee]['raw_tool_outputs'].get('calculate_utilization')})",
                "recommendation": f"Recommend reassigning task {rf['task_id']} away from {assignee}. {suggestion}{extra_note_str}"
            })
        elif is_over_budget:
            conflicts.append({
                "task_id": rf["task_id"],
                "assignee": assignee,
                "issue": f"Task {rf['task_id']} is high-risk and the project is over budget",
                "recommendation": f"Prioritize task {rf['task_id']} carefully - avoid adding paid resources given budget constraints.{extra_note_str}"
            })
        elif is_impeded:
            # High-risk + impediment, but no overload or budget issue - still worth flagging
            conflicts.append({
                "task_id": rf["task_id"],
                "assignee": assignee,
                "issue": f"Task {rf['task_id']} is high-risk and flagged as a sprint impediment",
                "recommendation": f"Investigate what's blocking task {rf['task_id']} - it has made no progress and is close to or past its deadline"
            })

    # Standalone warning: team is imbalanced even if no single task is currently in an escalated conflict above
    if is_imbalanced and not any(c.get("assignee") for c in conflicts):
        dist_result = distribution_findings[0]["raw_tool_outputs"].get("analyze_workload_distribution", "") if distribution_findings else ""
        conflicts.append({
            "task_id": None,
            "assignee": None,
            "issue": "Team workload distribution is imbalanced",
            "recommendation": f"No single task is currently escalated, but workload balance should be monitored: {dist_result}"
        })

    return conflicts
    
def orchestrate(project_data, project_id):
    all_findings = []
    all_findings.extend(run_risk_agent(project_data, project_id))
    all_findings.extend(run_resource_agent(project_data, project_id))
    all_findings.extend(run_budget_agent(project_data, project_id))
    all_findings.extend(run_scrum_master_agent(project_data, project_id))
    all_findings.extend(run_distribution_agent(project_data, project_id))
    conflicts = resolve_conflicts(all_findings, project_data)
    return all_findings, conflicts
if __name__ == "__main__":
    from db.repository import get_or_create_project

    with open("data/sample_project.json") as f:
        project_data = json.load(f)

    project_id = get_or_create_project("Demo Run")
    results, conflicts = orchestrate(project_data, project_id)

    print("=== Orchestrator Report ===\n")
    for r in results:
        identifier = r.get("task_id") or r.get("member") or "unknown"
        print(f"[{r['agent']}] {identifier}")
        if "planned_steps" in r:
            print(f"  Planned steps: {r['planned_steps']}")
        print(f"  VERIFIED Finding: {r['finding']}")
        if r.get("conflict"):
            print(f"  CONFLICT: LLM said '{r.get('llm_finding')}' but tools indicate '{r['finding']}'")
        print(f"  Tool outputs: {r['raw_tool_outputs']}")
        print(f"  User-facing response: {r['user_response']}")
        print()

    print("=== Memory: recent findings stored (from database) ===")
    for f in get_recent_findings(project_id):
        print(f"  [{f['agent_name']}] {f['target']}: {f['finding']} (saved at {f['created_at']})")

    print("\n=== Decision Engine: Conflicts & Recommendations ===")
    if conflicts:
        for c in conflicts:
            print(f"  {c['issue']}")
            print(f"  -> {c['recommendation']}\n")
    else:
        print("  No conflicts detected.")