"""add updated_at to team_member and budget_entry

Revision ID: 21d87f2e336c
Revises: b688129b96c2
Create Date: 2026-08-09 22:28:45.630106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d87f2e336c'
down_revision: Union[str, Sequence[str], None] = 'b688129b96c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_entries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('team_members', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'updated_at')
    op.drop_column('budget_entries', 'updated_at')
    # ### end Alembic commands ###
