"""add required_skill field to task

Revision ID: 384c930d826c
Revises: f7cff902a4c0
Create Date: 2026-08-14 12:24:57.745616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384c930d826c'
down_revision: Union[str, Sequence[str], None] = 'f7cff902a4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('required_skill', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'required_skill')
    # ### end Alembic commands ###
